# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game_Turn_History',
            new_name='Gamer',
        ),
    ]
