# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160930_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamer',
            name='no_Of_Trucks',
        ),
    ]
