# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_gamer_no_of_trucks'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='Nth_turn',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='gamer',
            name='brokerage_Cost',
            field=models.BigIntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='gamer',
            name='empty_Cost',
            field=models.BigIntegerField(default=400),
        ),
        migrations.AddField(
            model_name='gamer',
            name='loaded_Cost',
            field=models.BigIntegerField(default=550),
        ),
        migrations.AddField(
            model_name='gamer',
            name='unused_capital_cost',
            field=models.BigIntegerField(default=250),
        ),
    ]
