# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20161002_2205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gamer',
        ),
    ]
