# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0006_delete_gamer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_Type', models.CharField(max_length=20)),
                ('Number_of_players', models.PositiveIntegerField(default=1)),
                ('no_Of_Trucks', models.PositiveIntegerField(default=25)),
                ('Nth_turn', models.PositiveIntegerField(default=15)),
                ('empty_Cost', models.BigIntegerField(default=400)),
                ('loaded_Cost', models.BigIntegerField(default=550)),
                ('unused_capital_cost', models.BigIntegerField(default=250)),
                ('brokerage_Cost', models.BigIntegerField(default=1200)),
            ],
        ),
    ]
