# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_gamer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamer',
            name='Nth_turn',
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='brokerage_Cost',
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='empty_Cost',
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='loaded_Cost',
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='unused_capital_cost',
        ),
    ]
