# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20161003_1254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gamer',
            new_name='Games',
        ),
    ]
