# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20161004_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Reg_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.IntegerField()),
                ('Player_fname', models.CharField(max_length=150)),
                ('Player_Company', models.CharField(max_length=50)),
                ('Player_email', models.EmailField(max_length=254)),
                ('Player_passwd', models.CharField(default=5, max_length=10)),
                ('player_type', models.CharField(max_length=10)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('timestamp_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
