# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_player_reg_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_reg_details',
            name='PID',
            field=models.CharField(max_length=200),
        ),
    ]
